[Allgemein]
# Uhrzeit, zu der Tagesordnunng täglich aktualisiert werden soll (Zeitzone: Europa/Berlin)
uhrzeit = 03:00

[Wordpress]
benutzername = nutzer
passwort = passwort123

[Stud.IP]
benutzername = nutzer
passwort = passwort123

[DeepL]
auth_key = beispiel_key
